# Site settings
title: Musicall
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# External dependencies
gems: [jekyll-paginate]

# Local Config
baseurl: "https://adrianobrito.github.io/musicall" # the subpath of your site, e.g. /blog/
url: "https://adrianobrito.github.io/musicall" # the base hostname & protocol for your site
#baseurl: "/musicall/" # the subpath of your site, e.g. /blog/
#url: "http://localhost:4000"

# Remote Config
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://musicall.blog.br" # the base hostname & protocol for your site
categories: [Album,Single,Playlist,EP]
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
